#!/usr/bin/env python3
"""Generate the README parameter diagram from Helix 2D Flat geometry."""

from __future__ import annotations

import copy
import os
import sys
import xml.etree.ElementTree as ET


PROJECT_ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
if PROJECT_ROOT not in sys.path:
    sys.path.insert(0, PROJECT_ROOT)

import helix_2D_flatV3 as helix


SVG_NS = "http://www.w3.org/2000/svg"
ET.register_namespace("", SVG_NS)


def tag(name: str) -> str:
    return "{{{}}}{}".format(SVG_NS, name)


def add(parent: ET.Element, name: str, **attributes: object) -> ET.Element:
    normalized = {}
    for key, value in attributes.items():
        attribute_name = key[:-1] if key.endswith("_") else key
        normalized[attribute_name.replace("_", "-")] = str(value)
    return ET.SubElement(
        parent,
        tag(name),
        normalized,
    )


def add_text(
    parent: ET.Element,
    x: float,
    y: float,
    text: str,
    class_name: str = "measure-label",
    anchor: str = "middle",
    rotate: float | None = None,
) -> ET.Element:
    attributes = {
        "x": "{:.2f}".format(x),
        "y": "{:.2f}".format(y),
        "class": class_name,
        "text-anchor": anchor,
    }
    if rotate is not None:
        attributes["transform"] = "rotate({:.0f} {:.2f} {:.2f})".format(
            rotate, x, y
        )
    element = ET.SubElement(parent, tag("text"), attributes)
    element.text = text
    return element


def add_measure(
    parent: ET.Element,
    x1: float,
    y1: float,
    x2: float,
    y2: float,
) -> None:
    add(
        parent,
        "line",
        x1="{:.2f}".format(x1),
        y1="{:.2f}".format(y1),
        x2="{:.2f}".format(x2),
        y2="{:.2f}".format(y2),
        class_="measure",
    )


def add_extension(
    parent: ET.Element,
    x1: float,
    y1: float,
    x2: float,
    y2: float,
) -> None:
    add(
        parent,
        "line",
        x1="{:.2f}".format(x1),
        y1="{:.2f}".format(y1),
        x2="{:.2f}".format(x2),
        y2="{:.2f}".format(y2),
        class_="extension",
    )


def main() -> int:
    options = helix.DrawingOptions(
        show_numbers=False,
        terminal_labels=False,
        show_base_pair_lines=False,
        transparent=True,
    )
    sequence = "AG"
    rows = helix.make_rows(sequence, options)
    generated_root = ET.fromstring(helix.create_helix_svg(sequence, options))

    width = 1120
    height = 650
    scale = 1.2
    offset_x = 150.0
    offset_y = 145.0

    def px(value: float) -> float:
        return offset_x + scale * value

    def py(value: float) -> float:
        return offset_y + scale * value

    root = ET.Element(
        tag("svg"),
        {
            "width": str(width),
            "height": str(height),
            "viewBox": "0 0 {} {}".format(width, height),
        },
    )
    title = add(root, "title")
    title.text = "Helix 2D Flat geometry parameter definitions"
    description = add(root, "desc")
    description.text = (
        "A duplex generated by helix_2D_flatV3.py with measurement arrows "
        "derived from the same drawing geometry."
    )

    defs = add(root, "defs")
    marker = add(
        defs,
        "marker",
        id="arrow",
        markerWidth="8",
        markerHeight="8",
        refX="4",
        refY="4",
        orient="auto-start-reverse",
        markerUnits="strokeWidth",
    )
    add(marker, "path", d="M 0 0 L 8 4 L 0 8 z", fill="#2563a6")
    style = add(defs, "style")
    style.text = """
      .title { font: 700 27px Arial, Helvetica, sans-serif; fill: #111827; }
      .note { font: 15px Arial, Helvetica, sans-serif; fill: #4b5563; }
      .measure-label { font: 600 14px "Courier New", monospace; fill: #174f86; }
      .measure { fill: none; stroke: #2563a6; stroke-width: 1.6;
                 marker-start: url(#arrow); marker-end: url(#arrow); }
      .extension { fill: none; stroke: #7aa6cc; stroke-width: 1.1;
                   stroke-dasharray: 4 3; }
      .center { fill: #2563a6; }
    """

    add(root, "rect", width="100%", height="100%", fill="#ffffff")
    add(
        root,
        "rect",
        x="18",
        y="18",
        width=str(width - 36),
        height=str(height - 36),
        rx="16",
        fill="#f8fafc",
        stroke="#d9e2ec",
    )
    add_text(
        root,
        width / 2.0,
        48.0,
        "Geometry parameters",
        class_name="title",
    )
    add_text(
        root,
        width / 2.0,
        75.0,
        "The molecular drawing is generated directly by helix_2D_flatV3.py.",
        class_name="note",
    )

    molecule = add(
        root,
        "g",
        id="script-generated-duplex",
        transform="translate({:.2f} {:.2f}) scale({:.2f})".format(
            offset_x, offset_y, scale
        ),
    )
    for group_id in ("bonds", "nucleotides", "terminal-labels"):
        group = generated_root.find("{}[@id='{}']".format(tag("g"), group_id))
        if group is None:
            raise RuntimeError("Generated SVG is missing group {!r}".format(group_id))
        molecule.append(copy.deepcopy(group))

    measures = add(root, "g", id="geometry-measurements")
    top_row = rows[0]
    bottom_row = rows[1]
    top_geom = helix.make_base_geometry(top_row, options)
    bottom_geom = helix.make_base_geometry(bottom_row, options)

    top_base_y = py(top_geom["y"])
    top_base_bottom = py(top_geom["y"] + top_geom["h"])

    # Base widths.
    purine_x1 = px(top_geom["left_x"])
    purine_x2 = px(top_geom["left_x"] + top_geom["left_w"])
    pyrimidine_x1 = px(top_geom["right_x"])
    pyrimidine_x2 = px(top_geom["right_x"] + top_geom["right_w"])
    width_y = 125.0
    for x in (purine_x1, purine_x2, pyrimidine_x1, pyrimidine_x2):
        add_extension(measures, x, width_y, x, top_base_y)
    add_measure(measures, purine_x1, width_y, purine_x2, width_y)
    add_text(measures, (purine_x1 + purine_x2) / 2.0, 108.0, "purine_width")
    add_measure(measures, pyrimidine_x1, width_y, pyrimidine_x2, width_y)
    add_text(
        measures,
        (pyrimidine_x1 + pyrimidine_x2) / 2.0,
        108.0,
        "pyrimidine_width",
    )

    # Gap between a canonical purine-pyrimidine pair.
    pair_y = 170.0
    add_extension(measures, purine_x2, pair_y, purine_x2, top_base_y)
    add_extension(measures, pyrimidine_x1, pair_y, pyrimidine_x1, top_base_y)
    add_measure(measures, purine_x2, pair_y, pyrimidine_x1, pair_y)
    add_text(measures, (purine_x2 + pyrimidine_x1) / 2.0, 157.0, "pair_gap")

    # Vertical row spacing.
    row_x = 88.0
    top_row_y = py(top_row.y)
    bottom_row_y = py(bottom_row.y)
    add_extension(
        measures,
        row_x,
        top_row_y,
        px(helix.side_phosphate_x("left", options)),
        top_row_y,
    )
    add_extension(
        measures,
        row_x,
        bottom_row_y,
        px(helix.side_phosphate_x("left", options)),
        bottom_row_y,
    )
    add_measure(measures, row_x, top_row_y, row_x, bottom_row_y)
    add_text(
        measures,
        row_x - 18.0,
        (top_row_y + bottom_row_y) / 2.0,
        "row_spacing",
        rotate=-90.0,
    )

    # Vertical base height. Its label is also vertical.
    height_x = (purine_x2 + pyrimidine_x1) / 2.0
    add_measure(measures, height_x, top_base_y, height_x, top_base_bottom)
    add_text(
        measures,
        height_x + 18.0,
        (top_base_y + top_base_bottom) / 2.0,
        "base_height",
        rotate=-90.0,
    )

    # Sugar-to-base bond length, measured below the second left base.
    bottom_inward = helix.sugar_anchor("left", bottom_row.y, "inward", options)
    bond_x1 = px(bottom_inward[0])
    bond_x2 = px(bottom_geom["left_x"])
    bond_y = py(bottom_geom["y"] + bottom_geom["h"]) + 44.0
    add_extension(measures, bond_x1, py(bottom_row.y), bond_x1, bond_y)
    add_extension(measures, bond_x2, py(bottom_row.y), bond_x2, bond_y)
    add_measure(measures, bond_x1, bond_y, bond_x2, bond_y)
    add_text(
        measures,
        (bond_x1 + bond_x2) / 2.0,
        bond_y + 24.0,
        "base_bond_length",
    )

    # Horizontal sugar-to-kink segment on the second left residue.
    left_direction = helix.side_direction("left", options)
    five_anchor = helix.sugar_anchor(
        "left",
        bottom_row.y,
        helix.five_prime_anchor_name(left_direction),
        options,
    )
    kink_x = five_anchor[0] - options.phosphate_kink_length
    kink_y = py(five_anchor[1])
    add_measure(measures, px(kink_x), kink_y, px(five_anchor[0]), kink_y)
    add_text(
        measures,
        (px(kink_x) + px(five_anchor[0])) / 2.0,
        kink_y - 17.0,
        "phosphate_kink_length",
    )

    # Phosphate radius from the center to the right circumference.
    phosphate_center = helix.phosphate_center_for_residue(
        "left", 1, rows, options
    )
    phosphate_cx = px(phosphate_center[0])
    phosphate_cy = py(phosphate_center[1])
    add(measures, "circle", cx=phosphate_cx, cy=phosphate_cy, r="2.6", class_="center")
    add_measure(
        measures,
        phosphate_cx,
        phosphate_cy,
        px(phosphate_center[0] + options.phosphate_radius),
        phosphate_cy,
    )
    add_text(
        measures,
        phosphate_cx + scale * options.phosphate_radius / 2.0,
        phosphate_cy - 43.0,
        "phosphate_radius",
    )

    # Sugar radius from its center to C1'.
    sugar_center_x = px(options.left_sugar_x)
    sugar_center_y = py(top_row.y)
    sugar_c1 = helix.sugar_anchor("left", top_row.y, "C1", options)
    add(measures, "circle", cx=sugar_center_x, cy=sugar_center_y, r="2.6", class_="center")
    add_measure(
        measures,
        sugar_center_x,
        sugar_center_y,
        px(sugar_c1[0]),
        py(sugar_c1[1]),
    )
    add_text(
        measures,
        (sugar_center_x + px(sugar_c1[0])) / 2.0,
        sugar_center_y + 38.0,
        "sugar_radius",
    )

    add_text(
        root,
        width / 2.0,
        620.0,
        "ambiguous_width follows the same rectangle-width definition for IUPAC ambiguous bases.",
        class_name="note",
    )

    output_path = os.path.join(PROJECT_ROOT, "assets", "parameter_definitions.svg")
    tree = ET.ElementTree(root)
    ET.indent(tree, space="  ")
    tree.write(output_path, encoding="utf-8", xml_declaration=True)
    with open(output_path, "a", encoding="utf-8") as handle:
        handle.write("\n")
    print("Wrote {}".format(output_path))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
